### ISSUE TITLE
No way to toggle truncation programmatically with a prop

### ISSUE THREAD

**Issue by Soviut** [kavalcante/vue-truncate-collapsed#13]
I've inherited a project that uses vue-truncate-collapsed and was asked to make an "expand all" feature. Unfortunately, it seems like there's no documented prop to toggle or set the initial state of the truncation.

    <truncate :expanded="true">...</truncate>

**Comment by Soviut** [comment]
Solved by https://github.com/kavalcante/vue-truncate-collapsed/pull/14

**Comment by kavalcante** [comment]
Closing after merging #14
