### ISSUE TITLE
Show/Hide link showing when the content does not require truncation when type="html"

### ISSUE THREAD

**Issue by dgirgenti** [kavalcante/vue-truncate-collapsed#16]
When passing html into `text` with `type="html"`, I am seeing the Show/Hide link when there is nothing else to show. Clicking the link does nothing.

I believe this is because `v-if="text.length >= length"` naively includes the entire html string when `type="html"`, so though the dependency `html-truncate` can safely truncate the html, `vue-truncate-collapsed` does not correctly calculate when it needs to truncate since it's including all the html and not just the text.

**Comment by kavalcante** [comment]
Solved by #17
