### ISSUE TITLE
Remove "Show less" & add ... on text truncate

### ISSUE THREAD

**Issue by doitmax** [kavalcante/vue-truncate-collapsed#4]
Hey, two questions.

1. Is it possible to remove the "Show less" text completely?
2. Is there some way to add "..." at the end of the text and then add the "Show more" link like this:

<pre>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et
accusam et justo duo dolores et ea rebum... Show more</pre>

Cheers,
Dennis

**Comment by congtoanle** [comment]
Hi doitmax,
I downloaded only file vue and edit in this file. It will be ok if you want to remove or add anything in truncate component

**Comment by kavalcante** [comment]
Hello @doitmax, thanks for you issue.

As @congtoanle commented Vue-truncate-collapsed is a simple component, if you want to customize any of it you can do just downloading the component and importing into your application.

About the "Show Less", this can be easily, I will submit a PR soon.
