### ISSUE TITLE
Preserve html tags

### ISSUE THREAD

**Issue by jctiru** [kavalcante/vue-truncate-collapsed#8]
When using type="html" it strips the html tags. Is there any way to truncate the text but still preserving the tags? Like \<h3>This is a very long text\</h3> to \<h3>This is a very lo...\</h3>.

<h3>This is a very long text</h3> to <h3>This is a very lo...</h3>

**Comment by kavalcante** [comment]
I'm analyzing the problem yet. Can you have a reproduce link with a more complete example?

**Comment by jctiru** [comment]
Sorry but I don't know how to use jsfiddle but I can show you some screenshots:
![image](https://user-images.githubusercontent.com/34016067/36884618-0cea6a2e-1e1d-11e8-84ad-222cf57e8d9f.png)

Dev tools on truncate component: 
![image](https://user-images.githubusercontent.com/34016067/36884672-5b2a5604-1e1d-11e8-9c5c-519a6975021e.png)

Dev tools on the div with just a filter: 
![image](https://user-images.githubusercontent.com/34016067/36884865-85e9de68-1e1e-11e8-97fd-98e2f74cb66a.png)

My code: 
![image](https://user-images.githubusercontent.com/34016067/36884753-c362a8e8-1e1d-11e8-8f23-d70ed05a8275.png)


As you can see the truncate component effectively strips the html tags and converts(?) it all within a span tag. I thought that the html will be preserved but rather they are all stripped.

Sorry for all the screenshots but I really don't know how to use jsfiddle or other sandboxes. Thanks!

**Comment by alistairholt** [comment]
I would suggest that html2plaintext should be switched out for something that actually performs HTML truncation, not plain text truncation, e.g. https://github.com/huang47/nodejs-html-truncate.

**Comment by kavalcante** [comment]
Thanks for the indication, I'll see this.

**Comment by kavalcante** [comment]
Thanks @alistairholt for the indication, this new implementation is lighter and better :)

**Comment by alistairholt** [comment]
@kavalcante great news :)
